apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-restful-api
spec:
  selector:
    matchLabels:
      app: gin-restful-api
  template:
    metadata:
      labels:
        app: gin-restful-api
    spec:
      containers:
      - name: gin-restful-api
        image: phayao/gin-restful-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gin-restful-svc
spec:
  type: NodePort
  selector:
    app: gin-restful-api
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-svc
subsets:
  - addresses: 
      - ip: 192.168.1.34
    ports:
      - port: 3306
